resolver: lts-16.12
packages:
  - '.'
#  - '../servant-subscriber'
#  - '../purescript-bridge'
extra-deps:
  - purescript-bridge-0.8.0.0
  - servant-subscriber-0.7.0.0

flags: {}
 
extra-package-dbs: []

nix:
   shell-file: stack.nix
